version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    networks:
      - code-network
  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    environment:
      - DB_PORT=3306
      - DB_HOST=db
    networks:
      - code-network
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=dockerDrupal
    ports:
      - "3306:3306"
networks:
    code-network:
      driver: bridge
